/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Decision */
        post: operations["create_decision_api_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{person_id}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Person Skills */
        get: operations["person_skills_api_people__person_id__skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            parsed: components["schemas"]["ParsedRequisition"];
            dejareq: components["schemas"]["DejaReq"];
            redline: components["schemas"]["Redline"];
            ripple: components["schemas"]["Ripple"];
            options: components["schemas"]["Options"];
            brief: components["schemas"]["Brief"];
            data_quality: components["schemas"]["DataQuality"];
            tokens: components["schemas"]["Tokens"];
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Text */
            text: string;
        };
        /** AverageByDecision */
        AverageByDecision: {
            /** Decision */
            decision: string;
            /** Count */
            count: number;
            /** Avg Tenure Months */
            avg_tenure_months?: number | null;
            /** Avg Cost Lpa */
            avg_cost_lpa: number;
            /** Avg Time To Fill Days */
            avg_time_to_fill_days?: number | null;
        };
        /** Brief */
        Brief: {
            /** Sections */
            sections: components["schemas"]["BriefSection"][];
            /** Markdown */
            markdown: string;
            /** Html */
            html: string;
        };
        /** BriefSection */
        BriefSection: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Markdown */
            markdown: string;
        };
        /**
         * ConfidenceLabel
         * @enum {string}
         */
        ConfidenceLabel: "stated" | "inferred" | "computed" | "simulated";
        /** Constraint */
        Constraint: {
            /** Id */
            id: string;
            kind: components["schemas"]["ConstraintKind"];
            /** Value */
            value: string;
            /** Phrase */
            phrase: string;
            /** Span Start */
            span_start: number;
            /** Span End */
            span_end: number;
            source: components["schemas"]["ConstraintSource"];
            severity: components["schemas"]["Severity"];
            /** Hover Text */
            hover_text: string;
            cost: components["schemas"]["ConstraintCost"];
            /** Relaxed Value */
            relaxed_value?: string | null;
        };
        /** ConstraintCost */
        ConstraintCost: {
            /** Supply Delta */
            supply_delta?: number | null;
            /** Days Delta */
            days_delta?: number | null;
            /** Rupees Delta Lpa */
            rupees_delta_lpa?: number | null;
        };
        /**
         * ConstraintKind
         * @enum {string}
         */
        ConstraintKind: "location" | "years" | "skill" | "budget" | "deadline";
        /**
         * ConstraintSource
         * @enum {string}
         */
        ConstraintSource: "stated" | "inferred";
        /** ContractorCard */
        ContractorCard: {
            /** Person Id */
            person_id: string;
            /** Display Name */
            display_name: string;
            /** Fit */
            fit: number;
            /** Availability */
            availability: string;
            /** Extend Cost Lpa */
            extend_cost_lpa: number;
            /** Convert Saving Lpa */
            convert_saving_lpa?: number | null;
            /** Conversion Signal */
            conversion_signal: boolean;
            /** Compliance Flag */
            compliance_flag: boolean;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** DataQuality */
        DataQuality: {
            /** Conflicts */
            conflicts: number;
            /** Stale */
            stale: number;
            /** Self Report Only */
            self_report_only: number;
            /** Line */
            line: string;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Req Id */
            req_id: string;
            /** Option Id */
            option_id: string;
            verb: components["schemas"]["DecisionVerb"];
            /** Relaxed Mask */
            relaxed_mask: string;
            /** Decided By */
            decided_by: string;
            /** Reason */
            reason: string;
        };
        /**
         * DecisionVerb
         * @enum {string}
         */
        DecisionVerb: "Approve" | "Modify" | "Reject";
        /** DejaReq */
        DejaReq: {
            /** Match Count */
            match_count: number;
            /** Banner Text */
            banner_text?: string | null;
            /** Chip */
            chip?: string | null;
            /** Timeline */
            timeline: components["schemas"]["TimelineEntry"][];
            /** Averages By Decision */
            averages_by_decision: components["schemas"]["AverageByDecision"][];
            /** Patterns */
            patterns: components["schemas"]["Pattern"][];
            /** Insight Text */
            insight_text?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /** Cache Loaded */
            cache_loaded: boolean;
            /** Llm Configured */
            llm_configured: boolean;
        };
        /** IgnoredSource */
        IgnoredSource: {
            /** Source */
            source: string;
            /** Value */
            value: number;
            /** Reason */
            reason: string;
        };
        /** InternalCandidate */
        InternalCandidate: {
            /** Person Id */
            person_id: string;
            /** Display Name */
            display_name: string;
            /** Match */
            match: number;
            /** Band */
            band: string;
            /** Readiness Weeks */
            readiness_weeks?: number | null;
            /** Build Cost Lpa */
            build_cost_lpa?: number | null;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /**
         * Level
         * @enum {string}
         */
        Level: "junior" | "mid" | "senior" | "lead";
        /** MarketCard */
        MarketCard: {
            /** Location */
            location: string;
            /** Level */
            level: string;
            /** Supply */
            supply: number;
            /** Demand */
            demand: number;
            /** Sal P25 */
            sal_p25: number;
            /** Sal P50 */
            sal_p50: number;
            /** Sal P75 */
            sal_p75: number;
            /** Ttf P50 */
            ttf_p50: number;
            /** Ttf P80 */
            ttf_p80: number;
        };
        /** MixOption */
        MixOption: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Atoms */
            atoms: string[];
            /** Score */
            score: number;
            /** Ready By P80 Days */
            ready_by_p80_days: number;
            /** Year One Cost Lpa */
            year_one_cost_lpa: number;
            /** Reason */
            reason: string;
        };
        /** NetImpact */
        NetImpact: {
            /** Days To Fill Last Gap */
            days_to_fill_last_gap?: number | null;
            /** Total Cost Lpa */
            total_cost_lpa: number;
            /** Promotions */
            promotions: number;
            /** Red Flags */
            red_flags: number;
        };
        /** OptionCard */
        OptionCard: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** What It Means */
            what_it_means: string;
            /** Ready By P80 Days */
            ready_by_p80_days?: number | null;
            /** Year One Cost Lpa */
            year_one_cost_lpa?: number | null;
            /** Fit */
            fit?: string | null;
            /** Risk Label */
            risk_label: string;
            /** Risk Value */
            risk_value: number;
            /** Score */
            score?: number | null;
            /** Reason */
            reason: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** OptionSummary */
        OptionSummary: {
            /** Option Id */
            option_id: string;
            /** Name */
            name: string;
            /** Score */
            score?: number | null;
            /** Ready By P80 Days */
            ready_by_p80_days?: number | null;
            /** Year One Cost Lpa */
            year_one_cost_lpa?: number | null;
            /** Panel Line */
            panel_line: string;
        };
        /** OptionWeights */
        OptionWeights: {
            /** Speed */
            speed: number;
            /** Cost */
            cost: number;
            /** Fit */
            fit: number;
            /** Risk */
            risk: number;
            /** Strategic */
            strategic: number;
        };
        /** Options */
        Options: {
            /** Five */
            five: components["schemas"]["OptionCard"][];
            /** Mixes */
            mixes: components["schemas"]["MixOption"][];
            /** Relocate Card */
            relocate_card: components["schemas"]["RelocateRow"][];
            market_card: components["schemas"]["MarketCard"];
            /** Contractor Cards */
            contractor_cards: components["schemas"]["ContractorCard"][];
            /** Internal Candidates */
            internal_candidates: components["schemas"]["InternalCandidate"][];
            sourcing: components["schemas"]["Sourcing"];
            /** Decision Boundaries */
            decision_boundaries: string[];
            weights: components["schemas"]["OptionWeights"];
        };
        /** ParsedField */
        ParsedField: {
            /** Value */
            value?: string | number | null;
            /** Span */
            span?: string | null;
            /** Span Start */
            span_start?: number | null;
            /** Span End */
            span_end?: number | null;
            label: components["schemas"]["ConfidenceLabel"];
        };
        /** ParsedRequisition */
        ParsedRequisition: {
            /** Req Id */
            req_id: string;
            level: components["schemas"]["ParsedField"];
            headcount: components["schemas"]["ParsedField"];
            location: components["schemas"]["ParsedField"];
            work_mode: components["schemas"]["ParsedField"];
            min_years: components["schemas"]["ParsedField"];
            budget_lpa: components["schemas"]["ParsedField"];
            need_by_days: components["schemas"]["ParsedField"];
            duration_months: components["schemas"]["ParsedField"];
            criticality: components["schemas"]["ParsedField"];
            /** Skills */
            skills: components["schemas"]["ParsedSkill"][];
            title_normalization: components["schemas"]["TitleNormalization"];
        };
        /** ParsedSkill */
        ParsedSkill: {
            /** Skill Id */
            skill_id: string;
            importance: components["schemas"]["SkillImportance"];
            /** Confidence */
            confidence: number;
        };
        /** PastFinalist */
        PastFinalist: {
            /** Candidate Id */
            candidate_id: string;
            /** Stage Reached */
            stage_reached: string;
            /** Outcome */
            outcome: string;
            /** Decided On */
            decided_on: string;
            /** Open To Remote */
            open_to_remote: boolean;
        };
        /** Pattern */
        Pattern: {
            /** Name */
            name: string;
            /** Fired */
            fired: boolean;
            /** Text */
            text: string;
            /** Risk Option */
            risk_option?: string | null;
            /** Risk Penalty */
            risk_penalty: number;
        };
        /** Redline */
        Redline: {
            /** Constraints */
            constraints: components["schemas"]["Constraint"][];
            /** Constraint Order */
            constraint_order: components["schemas"]["ConstraintKind"][];
            /** Scenarios */
            scenarios: {
                [key: string]: components["schemas"]["ScenarioResult"];
            };
        };
        /** RelocateRow */
        RelocateRow: {
            /** Location */
            location: string;
            /** Supply */
            supply: number;
            /** Ttf P50 */
            ttf_p50: number;
            /** Ttf P80 */
            ttf_p80: number;
            /** Pay P50 Lpa */
            pay_p50_lpa: number;
            /** Score */
            score: number;
        };
        /** Ripple */
        Ripple: {
            /** Candidates */
            candidates: components["schemas"]["RippleCandidate"][];
        };
        /** RippleCandidate */
        RippleCandidate: {
            /** Person Id */
            person_id: string;
            /** Display Name */
            display_name: string;
            /** Match */
            match: number;
            chain: components["schemas"]["RippleNode"];
            net_impact: components["schemas"]["NetImpact"];
        };
        /** RippleNode */
        RippleNode: {
            /** Seat */
            seat: string;
            /** Person Id */
            person_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            status: components["schemas"]["RippleStatus"];
            /** Reason */
            reason: string;
            /** Children */
            children?: components["schemas"]["RippleNode"][];
        };
        /**
         * RippleStatus
         * @enum {string}
         */
        RippleStatus: "green" | "red" | "pending";
        /** ScenarioResult */
        ScenarioResult: {
            /** Top Option Id */
            top_option_id: string;
            /** Panel Text */
            panel_text: string;
            /** Options */
            options: components["schemas"]["OptionSummary"][];
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "red" | "amber" | "none";
        /**
         * SkillImportance
         * @enum {string}
         */
        SkillImportance: "must" | "nice";
        /** SkillScore */
        SkillScore: {
            /** Skill */
            skill: string;
            /** Value */
            value: number;
            /** Source */
            source: string;
            /** Observed On */
            observed_on: string;
            /** Confidence */
            confidence: number;
            /** Stale */
            stale: boolean;
            /** Conflict */
            conflict: boolean;
            /** Tooltip */
            tooltip: string;
            /** Ignored */
            ignored: components["schemas"]["IgnoredSource"][];
        };
        /** Sourcing */
        Sourcing: {
            /** Channels */
            channels: components["schemas"]["SourcingChannel"][];
            /** Past Finalists */
            past_finalists: components["schemas"]["PastFinalist"][];
            /** Suppliers */
            suppliers: components["schemas"]["SupplierRanking"][];
        };
        /** SourcingChannel */
        SourcingChannel: {
            /** Rank */
            rank?: number | null;
            /** Channel */
            channel: string;
            /** Evidence */
            evidence: string;
            /** Use For */
            use_for: string;
        };
        /** SupplierRanking */
        SupplierRanking: {
            /** Supplier Id */
            supplier_id: string;
            /** Name */
            name: string;
            /** Fill Rate */
            fill_rate: number;
            /** Median Days To Submit */
            median_days_to_submit: number;
            /** Avg Bill Rate */
            avg_bill_rate?: number | null;
        };
        /** TimelineEntry */
        TimelineEntry: {
            /** Req Id */
            req_id: string;
            /** Opened */
            opened: string;
            /** Decision */
            decision: string;
            /** Time To Fill Days */
            time_to_fill_days?: number | null;
            /** Ramp Note */
            ramp_note?: string | null;
            /** First Year Cost Lpa */
            first_year_cost_lpa: number;
            /** Outcome Text */
            outcome_text: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** TitleMapping */
        TitleMapping: {
            /** Raw Title */
            raw_title: string;
            /** Source System */
            source_system: string;
            /** Role */
            role: string;
            level?: components["schemas"]["Level"] | null;
            method: components["schemas"]["TitleMethod"];
            /** Confidence */
            confidence: number;
            /** Esco Uri */
            esco_uri?: string | null;
            /** Onet Code */
            onet_code?: string | null;
        };
        /**
         * TitleMethod
         * @enum {string}
         */
        TitleMethod: "esco_alt" | "onet" | "manual" | "fuzzy";
        /** TitleNormalization */
        TitleNormalization: {
            /** Raw Titles Count */
            raw_titles_count: number;
            /** Role */
            role: string;
            /** Levels */
            levels: components["schemas"]["Level"][];
            /** Mappings */
            mappings: components["schemas"]["TitleMapping"][];
        };
        /** Tokens */
        Tokens: {
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Hit */
            cache_hit: boolean;
            /** Est Cost */
            est_cost: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: {
                stub?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_decision_api_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    person_skills_api_people__person_id__skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillScore"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
